/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.moodanalyser;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import com.moodanalyser.MoodAnalyser;
import org.junit.Assert;

public class MoodAnalyserTest {
 
    
    @Test public void whennotsad() {
        MoodAnalyser moodan = new MoodAnalyser();

       String mood = null;
	try {
		ExpectedException exceptionrule=ExpectedException.none();
		exceptionrule.expect(MoodAnalysisException.class);
		mood = moodan.analysemood(null);
	    Assert.assertEquals("HAPPY",mood);

	} catch (MoodAnalysisException e) {
		e.printStackTrace();
	}
    }
       
    
    
    	
}