/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.moodanalyser;

import org.junit.Test;

import com.moodanalyser.MoodAnalyser;

import org.junit.Assert;

public class MoodAnalyserTest {
    @Test public void whensad() {
        MoodAnalyser moodan = new MoodAnalyser();
       String mood=moodan.analysemood("I am in Sad Mood");
       Assert.assertEquals("SAD",mood);
    }
    
    @Test public void whennotsad() {
        MoodAnalyser moodan = new MoodAnalyser();
       String mood=moodan.analysemood("I am in Happy Mood");
       Assert.assertEquals("HAPPY",mood);
    }
}       
