/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.moodanalyser;

public class MoodAnalyser {
	
	private String message;
	
	public MoodAnalyser(String msg)
	{
		this.message=msg;
	}
	
    public String analysemood() {
       if(message.contains("Sad"))
    		   return "SAD";
       else 
    	   return "HAPPY";
    }
    
    
}