/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.moodanalyser;

public class MoodAnalyser{
public String analysemood(String msg) {
	
    if(msg.contains("Sad"))
 		   return "SAD";
    else 
 	   return "HAPPY";
 }}