/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.moodanalyser;
//import org.junit.rules.ExpectedException;
//import org.junit.*;
public class MoodAnalyser {
	

	
    public String analysemood(String message) throws MoodAnalysisException {
    	try {	
	   if(message.length()==0)
    			throw new MoodAnalysisException(MoodAnalysisException.ExceptionType.ENTERED_EMPTY,"Please enter valid mood");
    		
       if(message.contains("Sad"))
    		   return "SAD";
       else 
    	   return "HAPPY";
    }catch(NullPointerException e)
    	{
    	System.out.println("Exception Thrown");
    	throw new MoodAnalysisException(MoodAnalysisException.ExceptionType.ENTERED_NULL,"Please enter valid mood");
    	}
    	
    
}}